In [1]:
# task 1
import numpy as np

# Create a one-dimensional array with the first 10 natural numbers
vector = np.arange(1, 11)

# Print the values of the vector
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# task 2
import numpy as np

# Create a 3x3 matrix filled with zeros
matrix = np.zeros((3, 3))

# Print the values of the matrix
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# task 3
import numpy as np

# Create a 5x5 matrix filled with random integers in the range of 1 to 10
matrix = np.random.randint(1, 11, size=(5, 5))

# Print the values of the matrix
print(matrix)

[[ 6  6  4  7  1]
 [ 6  1  9 10 10]
 [ 6  5  1  9  4]
 [10  3  8  1  7]
 [ 5  7  8  9  7]]


In [4]:
# task 4
import numpy as np

# Create a 4x4 matrix filled with random floating-point numbers in the range of 0 to 1
matrix = np.random.rand(4, 4)

# Print the values of the matrix
print(matrix)

[[0.51599303 0.03992134 0.20546283 0.24088183]
 [0.26740419 0.35661438 0.2709782  0.32725397]
 [0.49877941 0.37649449 0.20315686 0.19482914]
 [0.7360736  0.60654149 0.80711104 0.13321254]]


In [5]:
# task 5
import numpy as np

# Create two 1-dimensional arrays of size 5 filled with random integers in the range of 1 to 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Perform element-wise addition, subtraction, and multiplication
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Print the results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Addition: [ 7 11 11  8  2]
Subtraction: [ 1  1 -3  0  0]
Multiplication: [12 30 28 16  1]


In [21]:
# task 6
import numpy as np

# Create two 1-dimensional arrays (vectors) of size 7 filled with random integers
vector1 = np.random.randint(1, 11, size=7)
vector2 = np.random.randint(1, 11, size=7)

# Find the dot product (scalar product) of the two vectors
dot_product = np.dot(vector1, vector2)

# Print the result
print(vector1)
print(vector2)
print("Dot product:", dot_product)

[ 6 10  4  1  3  3  1]
[2 6 1 7 3 2 5]
Dot product: 103


In [22]:
# task 7
import numpy as np

# Create a 2x2 matrix filled with random integers in the range of 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))

# Create a 2x3 matrix filled with random integers in the range of 1 to 10
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Multiply the two matrices
product = np.dot(matrix1, matrix2)

# Print the result
print(matrix1)
print(matrix2)
print("Product of the two matrices:\n", product)

[[5 7]
 [1 1]]
[[5 9 9]
 [2 8 6]]
Product of the two matrices:
 [[ 39 101  87]
 [  7  17  15]]


In [25]:
# task 8
import numpy as np

# Create a 3x3 matrix filled with random integers in the range of 1 to 10
matrix = np.random.randint(1, 11, size=(3, 3))
print(matrix)

# Find the inverse of the matrix
inverse = np.linalg.inv(matrix)

# Print the result
print("Inverse of the matrix:\n", inverse)

[[10  4  7]
 [ 1  6  4]
 [ 2 10  3]]
Inverse of the matrix:
 [[ 0.10280374 -0.27102804  0.12149533]
 [-0.02336449 -0.07476636  0.15420561]
 [ 0.00934579  0.42990654 -0.26168224]]


In [26]:
# task 9
import numpy as np

# Create a 4x4 matrix filled with random floating-point numbers in the range of 0 to 1
matrix = np.random.rand(4, 4)
print(matrix)

# Transpose the matrix
transposed = matrix.T

# Print the result
print("Transposed matrix:\n", transposed)

[[0.48288587 0.71971772 0.4661058  0.81531144]
 [0.66533925 0.20390271 0.7181393  0.15239369]
 [0.95788057 0.70586166 0.74044957 0.59792298]
 [0.65196769 0.60305239 0.64188881 0.84331566]]
Transposed matrix:
 [[0.48288587 0.66533925 0.95788057 0.65196769]
 [0.71971772 0.20390271 0.70586166 0.60305239]
 [0.4661058  0.7181393  0.74044957 0.64188881]
 [0.81531144 0.15239369 0.59792298 0.84331566]]


In [27]:
# task 10
import numpy as np

# Create a 3x4 matrix filled with random integers in the range of 1 to 10
matrix = np.random.randint(1, 11, size=(3, 4))
print(matrix)

# Create a 4-dimensional vector filled with random integers in the range of 1 to 10
vector = np.random.randint(1, 11, size=4)
print(vector)

# Multiply the matrix by the vector
product = np.dot(matrix, vector)

# Print the result
print("Product of the matrix and the vector:", product)

[[ 5  9 10  1]
 [ 1  5  9  8]
 [ 5  9  5  1]]
[3 3 1 3]
Product of the matrix and the vector: [55 51 50]


In [28]:
# task 11
import numpy as np

# Create a 2x3 matrix filled with random floating-point numbers in the range of 0 to 1
matrix = np.random.rand(2, 3)
print(matrix)

# Create a 3-dimensional vector filled with random floating-point numbers in the range of 0 to 1
vector = np.random.rand(3)
print(vector)

# Multiply the matrix by the vector
product = np.dot(matrix, vector)

# Print the result
print("Product of the matrix and the vector:", product)

[[0.26764245 0.34910924 0.15616979]
 [0.61740932 0.86882985 0.47164188]]
[0.31427209 0.5721786  0.41309332]
Product of the matrix and the vector: [0.34837809 0.88599247]


In [29]:
# task 12
import numpy as np

# Create two 2x2 matrices filled with random integers in the range of 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Perform element-wise multiplication
elementwise_product = np.multiply(matrix1, matrix2)

# Print the result
print(matrix1)
print(matrix2)
print("Element-wise product of the two matrices:\n", elementwise_product)

[[10  9]
 [ 1  4]]
[[2 1]
 [4 6]]
Element-wise product of the two matrices:
 [[20  9]
 [ 4 24]]


In [30]:
# task 13
import numpy as np

# Create two 2x2 matrices filled with random integers in the range of 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Multiply the two matrices
product = np.dot(matrix1, matrix2)

# Print the result
print(matrix1)
print(matrix2)
print("Product of the two matrices:\n", product)

[[ 3  9]
 [ 2 10]]
[[8 8]
 [4 5]]
Product of the two matrices:
 [[60 69]
 [56 66]]


In [31]:
# task 14
import numpy as np

# Create a 5x5 matrix filled with random integers in the range of 1 to 100
matrix = np.random.randint(1, 101, size=(5, 5))

# Find the sum of the elements in the matrix
sum_of_elements = np.sum(matrix)

# Print the result
print(matrix)
print("Sum of the elements in the matrix:", sum_of_elements)

[[ 45  69  24  66  57]
 [ 88  18  23  68  48]
 [ 36  25  89   5  30]
 [ 34  17 100  69  86]
 [ 52  11  86   4  67]]
Sum of the elements in the matrix: 1217


In [32]:
# task 15
import numpy as np

# Create two 4x4 matrices filled with random integers in the range of 1 to 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Find the difference between the two matrices
difference = matrix1 - matrix2

# Print the result
print(matrix1)
print(matrix2)
print("Difference between the two matrices:\n", difference)

[[9 1 4 5]
 [4 9 8 9]
 [2 2 1 8]
 [9 7 5 8]]
[[ 1  8  6  9]
 [ 4  7  9  1]
 [ 1  6  2  6]
 [ 6  6  3 10]]
Difference between the two matrices:
 [[ 8 -7 -2 -4]
 [ 0  2 -1  8]
 [ 1 -4 -1  2]
 [ 3  1  2 -2]]


In [33]:
# task 16
import numpy as np

# Create a 3x3 matrix filled with random floating-point numbers in the range of 0 to 1
matrix = np.random.rand(3, 3)

# Find the sum of the elements in each row
row_sums = np.sum(matrix, axis=1)

# Print the result
print(matrix)
print("Vector-column containing the sum of the elements in each row:\n", row_sums)

[[0.93480306 0.41956748 0.2235064 ]
 [0.94251561 0.44001569 0.90372798]
 [0.91264066 0.85036937 0.02041105]]
Vector-column containing the sum of the elements in each row:
 [1.57787695 2.28625928 1.78342108]


In [34]:
# task 17
import numpy as np

# Create a 3x4 matrix filled with random integers
matrix = np.random.randint(1, 11, size=(3, 4))

# Create a new matrix with the squares of the numbers in the original matrix
squared_matrix = np.square(matrix)

# Print the result
print(matrix)
print("Matrix with the squares of the numbers in the original matrix:\n", squared_matrix)

[[10 10  6  7]
 [ 5  3  1  6]
 [ 9 10  4  5]]
Matrix with the squares of the numbers in the original matrix:
 [[100 100  36  49]
 [ 25   9   1  36]
 [ 81 100  16  25]]


In [35]:
# task 18
import numpy as np

# Create a 4-dimensional vector filled with random integers in the range of 1 to 50
vector = np.random.randint(1, 51, size=4)

# Find the square roots of the numbers in the vector
square_roots = np.sqrt(vector)

# Print the result
print(vector)
print("Vector with the square roots of the numbers in the original vector:", square_roots)

[28 24 30 45]
Vector with the square roots of the numbers in the original vector: [5.29150262 4.89897949 5.47722558 6.70820393]
